[[annotation]]
file="/mnt/d/Bioinformatics/NGS/GENOMICS/Joint_genotyping/refs/process_files/clinvar_20260530.vcf.gz"
fields = ["AF_EXAC","CLNSIG","CLNHGVS","ORIGIN"]
names = ["AF_EXAC","CLNSIG","CLNHGVS","ORIGIN"]
ops=["self","self","self","self"]
